name: freedompay
description: "A Flutter plugin for FreedomPay payment processing, supporting both Android and iOS platforms."
version: 0.0.3
homepage: https://github.com/aibekdv/freedompay
repository: https://github.com/aibekdv/freedompay
issue_tracker: https://github.com/aibekdv/freedompay/issues
license: MIT

# Specify the Dart SDK version and Flutter version compatibility.
environment:
  sdk: ^3.0.0
  flutter: ">=3.3.0"

# Dependencies
dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

# dev dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      android:
        package: kg.neosoft.freedompay
        pluginClass: FreedompayPlugin
      ios:
        pluginClass: FreedompayPlugin
